### ISSUE TITLE
This seems abandoned but - its broken in BigSur

### ISSUE THREAD

**Issue by oniGino** [greenboxal/dns-heaven#8]
Was working great, seems to be broken in bigsur, any way to get this fixed?

**Comment by planetlabs-admin** [comment]
@oniGino what exactly is broken in Big Sur? Are you running on an M1/ARM Mac? 

I ask because I was about to deploy this to my fleet, some of which are Big Sur macos (mixed Intel and ARM).

**Comment by rrrix** [comment]
@oniGino what exactly is broken in Big Sur? Are you running on an M1/ARM Mac?

I ask because I was about to deploy this to my fleet, some of which are Big Sur macos (mixed Intel and ARM).

**Comment by oniGino** [comment]
no not m1

ever since the os upgrade it stopped forwarding DNS.

no clue why, my dnsutils settings look correct still

**Comment by oniGino** [comment]
I'm using https://github.com/jduepmeier/dns-heaven via homebrew and things seems good, going to close this, thanks
